package job

const ERROR_JOB = 0x5000

const ERROR_JOB_NOT_FOUND_ALIAS = ERROR_JOB + 1

const ERROR_JOB_NOT_FOUND_ID = ERROR_JOB + 2

const ERROR_JOB_NOT_FOUND = ERROR_JOB + 3

const ERROR_JOB_NOT_FOUND_VERSION = ERROR_JOB + 4

const ERROR_JOB_STATUS = ERROR_JOB + 5

const ERROR_JOB_NOT_FOUND_PREFIX = ERROR_JOB + 6

const ERROR_JOB_NOT_FOUND_TOKEN = ERROR_JOB + 7

const ERROR_JOB_NOT_FOUND_SLAVE = ERROR_JOB + 8

const ERROR_JOB_AUTH = ERROR_JOB + 9
